# .github/workflows/devy_scraper.yml
name: Run Devy Scraper

on:
  schedule:
    # Run every day at 9:00 AM UTC (adjust as needed)
    - cron: '0 9 * * *'
  workflow_dispatch:
    # Allows manual triggering from the GitHub Actions tab

jobs:
  scrape_devy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-3.10' # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Devy Scraper script
      working-directory: scripts/scrapers
      run: python devy_scaper.py
      env:
        # Pass database credentials from GitHub Secrets
        # Ensure these secrets are configured in your GitHub repository settings
        NEON_HOST: ${{ secrets.NEON_HOST }}
        NEON_DATABASE: ${{ secrets.NEON_DATABASE }}
        NEON_USER: ${{ secrets.NEON_USER }}
        NEON_PASSWORD: ${{ secrets.NEON_PASSWORD }}
        NEON_PORT: ${{ secrets.NEON_PORT }}
        # sslmode='require' is handled in the Python script's connection parameters