name: Run NFL and CFB Scripts Weekly

on:
  schedule:
    # Run both scripts at 9:00 PM UTC (5:00 PM Eastern Time) on Sundays
    - cron: '0 21 * * 0'
    # Run both scripts at 1:30 PM UTC (9:30 AM Eastern Time) on Mondays
    - cron: '30 13 * * 1'
  workflow_dispatch: # Add this line to enable manual triggering

jobs:
  run_scripts:
    name: Run NFL and CFB Scripts
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R Packages
      env:
        GITHUB_PAT: ${{ secrets.GH_PAT }}
      run: |
        Rscript -e 'install.packages("remotes")'
        Rscript -e 'remotes::install_github("nflverse/nflverse")'
        Rscript -e 'install.packages(c("tidyverse", "lubridate", "jsonlite"))'

    - name: Run nflfastR Script
      run: Rscript nflfastR.r

    # - name: Run cfbfastR Script
    #  run: Rscript cfbfastR.r

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update nfl-schedules.js file after running R script"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}