name: Run NFL and CFB Scripts Weekly
        
on:
  schedule:
    # Run both scripts at 9:00 PM UTC (5:00 PM Eastern Time) on Sundays
    - cron: '0 21 * * 0'
    # Run both scripts at 1:30 PM UTC (9:30 AM Eastern Time) on Mondays
    - cron: '30 13 * * 1'
  workflow_dispatch:

jobs:
  run_scripts:
    name: Run NFL and CFB Scripts
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ runner.temp }}/RLibrary
        key: ${{ runner.os }}-r-${{ hashFiles('**/*.r') }}-${{ hashFiles('**/*.lock') }}-${{ runner.architecture }}
        restore-keys: |
          ${{ runner.os }}-r-

    - name: Install R Packages
      env:
        GITHUB_PAT: ${{ secrets.GH_PAT }}
        R_LIBS_USER: ${{ runner.temp }}/RLibrary
      run: |
        Rscript -e 'install.packages("remotes", lib = Sys.getenv("R_LIBS_USER"))'
        Rscript -e 'remotes::install_github("nflverse/nfl4th", lib = Sys.getenv("R_LIBS_USER"))'
        Rscript -e 'remotes::install_github("nflverse/nflfastR", lib = Sys.getenv("R_LIBS_USER"))'
        Rscript -e 'remotes::install_github("nflverse/nflplotR", lib = Sys.getenv("R_LIBS_USER"))'
        Rscript -e 'remotes::install_github("nflverse/nflreadr", lib = Sys.getenv("R_LIBS_USER"))'
        Rscript -e 'remotes::install_github("nflverse/nflseedR", lib = Sys.getenv("R_LIBS_USER"))'
        Rscript -e 'install.packages(c("nflverse", "tidyverse", "lubridate", "jsonlite", "dplyr"), lib = Sys.getenv("R_LIBS_USER"))'
        
    - name: Check Installed Packages
      env:
        R_LIBS_USER: ${{ runner.temp }}/RLibrary
      run: |
        echo "Listing installed R packages:"
        Rscript -e '.libPaths(); installed.packages()[,1]'

    - name: Update season year in script
      run: |
        CURRENT_YEAR=$(date +%Y)
        echo "Using NFL season year: $CURRENT_YEAR"
        # Replace any hardcoded year with the current year
        sed -i "s/load_schedules(seasons = [0-9]\{4\})/load_schedules(seasons = $CURRENT_YEAR)/g" nflfastR.r

    - name: Run nflfastR Script
      env:
        R_LIBS_USER: ${{ runner.temp }}/RLibrary
      run: |
        Rscript nflfastR.r
        if [ $? -ne 0 ]; then
          echo "R script execution failed"
          cat error_log.txt || echo "No error log found"
          exit 1
        fi

    # - name: Run cfbfastR Script
    #   run: Rscript cfbfastR.r

    - name: Detect Changes
      id: detect_changes
      run: |
        changes=$(git status --porcelain)
        echo "changes_detected=$([[ -n "$changes" ]] && echo "true" || echo "false")" >> $GITHUB_OUTPUT
        echo "Changes detected: $changes"
        
    - name: Commit and push changes
      if: steps.detect_changes.outputs.changes_detected == 'true'
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update nfl-schedules.js file after running R script"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}