name: Run NFL and CFB Scripts Weekly

on:
  schedule:
    # Run both scripts at 5:00 PM on Sundays
    - cron: '0 17 * * 0'
    # Run both scripts at 9:30 AM on Mondays
    - cron: '30 9 * * 1'

jobs:
  run_scripts:
    name: Run NFL and CFB Scripts
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # This checks out your repository

    - name: Set up R
      uses: r-lib/actions/setup-r@v2  # This sets up R

    - name: Run nflfastR Script
      run: Rscript nflfastR.r  # This runs the nflfastR script

    # - name: Run cfbfastR Script
    #  run: Rscript cfbfastR.r  # This runs the cfbfastR script

    - name: Commit and push changes  # This commits and pushes changes back to the repo
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update nfl-schedules.js file after running R script"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This token allows pushing to the repo